<#
.SYNOPSIS
    Stores SFTP credentials securely in Azure Key Vault.

.DESCRIPTION
    This module is responsible for storing SFTP secrets in Azure Key Vault.

    Responsibilities:
    - Validate the Key Vault name.
    - Validate the secret name.
    - Validate that a password was supplied.
    - Convert the password into a secure string.
    - Store the password as an Azure Key Vault secret.
    - Verify that the secret was successfully created.

    This module does NOT:
    - Create the SFTP local user.
    - Generate the SFTP password.
    - Configure SFTP permissions.
    - Print the password.
    - Write the password to log files.

.NOTES
    The caller is responsible for generating/capturing the password.
#>

function Set-SftpPasswordInKeyVault {

    [CmdletBinding()]
    param (

        # Name of the Azure Key Vault
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$KeyVaultName,

        # Name under which the password will be stored
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [ValidatePattern("^[a-zA-Z0-9-]+$")]
        [string]$SecretName,

        # SFTP password generated by Azure
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [SecureString]$Password
    )

    try {

        Write-Host "----------------------------------------"
        Write-Host "Key Vault Secret Provisioning"
        Write-Host "----------------------------------------"

        # ------------------------------------------------------------
        # 1. Verify that the required Az.KeyVault cmdlet exists
        # ------------------------------------------------------------

        if (-not (Get-Command Set-AzKeyVaultSecret -ErrorAction SilentlyContinue)) {

            throw "Set-AzKeyVaultSecret cmdlet is not available. Install/import Az.KeyVault."
        }

        # ------------------------------------------------------------
        # 2. Verify that the Key Vault exists
        # ------------------------------------------------------------

        Write-Verbose "Checking Key Vault '$KeyVaultName'..."

        $keyVault = Get-AzKeyVault `
            -VaultName $KeyVaultName `
            -ErrorAction Stop

        if ($null -eq $keyVault) {

            throw "Key Vault '$KeyVaultName' was not found."
        }

        # ------------------------------------------------------------
        # 3. Store the password as a Key Vault secret
        #
        # IMPORTANT:
        # The password is never converted to plain text here.
        # ------------------------------------------------------------

        Write-Host "Storing SFTP credential securely in Key Vault..."

        $secret = Set-AzKeyVaultSecret `
            -VaultName $KeyVaultName `
            -Name $SecretName `
            -SecretValue $Password `
            -ErrorAction Stop

        if ($null -eq $secret) {

            throw "Key Vault did not return a secret object."
        }

        # ------------------------------------------------------------
        # 4. Verify that the secret exists
        # ------------------------------------------------------------

        Write-Host "Verifying Key Vault secret..."

        $verification = Get-AzKeyVaultSecret `
            -VaultName $KeyVaultName `
            -Name $SecretName `
            -ErrorAction Stop

        if ($null -eq $verification) {

            throw "Key Vault secret verification failed."
        }

        # ------------------------------------------------------------
        # 5. Return metadata only.
        #
        # NEVER return the password itself.
        # ------------------------------------------------------------

        Write-Host "SFTP credential stored successfully."
        Write-Host "Secret Name: $SecretName"

        return [PSCustomObject]@{
            KeyVaultName = $KeyVaultName
            SecretName   = $SecretName
            SecretId     = $verification.Id
            Stored       = $true
        }
    }
    catch {

        Write-Error @"
Failed to store SFTP credential in Key Vault.

Key Vault   : $KeyVaultName
Secret Name : $SecretName

Error:
$($_.Exception.Message)
"@

        throw
    }
}